
name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  execute-regression:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        platform: [x86, x64]
        compiler: [gnu, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@v1.1
        with:
          run-regression: false
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@v1.1
        with:
          download-exotic-libraries: false
          test-folder-recursive: false
          run-regression: true
          test-folders: |
            test/
          test-exclude-file-pattern: |
            mock+
            crash_test.c
          test-exclude-file-pattern-windows: |
            test_struct_fields_types_clean+
          compiler-options-for-tests: |
            -I.
            -I./test/structs
            -I./include/
            
  build-and-deploy-gh_pages:
    runs-on: ubuntu-latest
    needs: execute-regression
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          sudo apt-get install -y python3 python3-setuptools python3-pip python3-sphinx
          python -m pip install --upgrade pip
          python -m pip install themata m2r2
          sudo apt-get install -y clang doxygen make
          cd ./docs/
          sudo bash ./make.sh
          cd ../

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_CI_CD }}
          BRANCH: gh-pages 
          FOLDER: docs/build/html
          CLEAN: true
            
        
